package feishu

import (
	"strings"
	"unicode/utf8"
)

// MaxCardContentBytes is the practical per-element content budget for Feishu
// interactive cards. Feishu rejects a card whose content is larger than about
// 30KB, so 25000 bytes leaves headroom for the card envelope (msg_type,
// header, escaping). MarkdownToCardElements splits oversized content on line
// boundaries so that no element it returns exceeds this budget.
//
// The single exception is a markdown line that is itself larger than the
// budget (for example one enormous unbroken paragraph): such a line cannot be
// split at a line boundary, so it is broken on a rune boundary instead.
const MaxCardContentBytes = 25000

// defaultCardTitleMaxLen is the title length used by CardTitleFromMarkdown when
// the caller passes maxLen <= 0.
const defaultCardTitleMaxLen = 40

// defaultCardTitle is returned by CardTitleFromMarkdown when the input contains
// nothing usable as a title.
const defaultCardTitle = "huan-agent"

// CardElement is one element in a Feishu interactive card.
//
// The supported shapes are:
//
//	{"tag":"div","text":{"tag":"lark_md","content":"..."}}           markdown block
//	{"tag":"hr"}                                                     horizontal divider
//	{"tag":"note","elements":[{"tag":"plain_text","content":"..."}]} small footnote
//
// Fenced code lives inside a div's lark_md content (Feishu renders it as a
// code block), so no dedicated code element is needed. The note shape is built
// by leaving Text nil and filling Elements; it is handy for a
// "Generated by huan-agent" style footer.
type CardElement struct {
	Tag      string     `json:"tag"`
	Text     *CardText  `json:"text,omitempty"`
	Elements []CardText `json:"elements,omitempty"`
}

// CardText is a text/media payload inside a card element. Tag is "lark_md" for
// markdown content and "plain_text" for verbatim text.
type CardText struct {
	Tag     string `json:"tag"`
	Content string `json:"content"`
}

// MarkdownBlock is a chunk of markdown with its kind.
type MarkdownBlock struct {
	// Kind is "text" or "code".
	Kind string
	// Content is the raw markdown (including the fences for Kind == "code").
	Content string
	// Language is the fence info string for Kind == "code" (e.g. "go"), else "".
	Language string
}

// MarkdownToCardElements converts a markdown string into Feishu card elements.
//
// Every text or code block becomes a div element whose lark_md content is the
// block's markdown verbatim (code fences are kept intact so Feishu renders
// them as code), and an hr divider is inserted between consecutive blocks —
// never before the first or after the last one.
//
// Elements whose content would exceed MaxCardContentBytes are split into
// several div elements on line boundaries; oversized code blocks are re-opened
// and re-closed with their fence so every part stays valid markdown.
//
// The returned slice is always non-nil. An empty or whitespace-only input
// yields a single div element with empty content, so callers always have
// something valid to render.
func MarkdownToCardElements(md string) []CardElement {
	blocks := SplitMarkdownBlocks(md)
	elements := make([]CardElement, 0, 2*len(blocks))
	for _, b := range blocks {
		if strings.TrimSpace(b.Content) == "" {
			continue // defence in depth: SplitMarkdownBlocks already drops these
		}
		if len(elements) > 0 {
			elements = append(elements, CardElement{Tag: "hr"})
		}
		for _, part := range cardContentParts(b) {
			elements = append(elements, CardElement{
				Tag:  "div",
				Text: &CardText{Tag: "lark_md", Content: part},
			})
		}
	}
	if len(elements) == 0 {
		return []CardElement{{Tag: "div", Text: &CardText{Tag: "lark_md", Content: ""}}}
	}
	return elements
}

// cardContentParts returns the lark_md contents to render for a single block,
// honouring MaxCardContentBytes.
func cardContentParts(b MarkdownBlock) []string {
	if len(b.Content) <= MaxCardContentBytes {
		return []string{b.Content} // fast path: content passes through verbatim
	}
	if b.Kind == "code" {
		return splitCodeBlock(b)
	}
	return splitContentByLines(b.Content, MaxCardContentBytes)
}

// SplitMarkdownBlocks splits markdown into blocks suitable for separate card
// elements: fenced code blocks (``` or ~~~) are kept whole — including an
// unterminated fence at EOF, which is treated as code running to the end of the
// input — while paragraphs separated by a blank line become separate blocks.
// Content inside a fence is never split, so a blank line inside a code block
// does not end the block. The opening fence's info string is captured as the
// block's Language.
//
// Completely blank blocks are dropped and the result is always non-nil, so
// empty or whitespace-only input yields an empty slice.
func SplitMarkdownBlocks(md string) []MarkdownBlock {
	blocks := make([]MarkdownBlock, 0, 4)
	lines := strings.Split(normalizeNewlines(md), "\n")

	var para []string      // lines of the pending paragraph
	var fenced []string    // lines of the pending fenced block, opening fence included
	var fence, lang string // current fence run (e.g. "```") and its info string

	flushPara := func() {
		if len(para) == 0 {
			return
		}
		content := strings.TrimRight(strings.Join(para, "\n"), " \t")
		para = para[:0]
		if strings.TrimSpace(content) == "" {
			return
		}
		blocks = append(blocks, MarkdownBlock{Kind: "text", Content: content})
	}
	flushFence := func() {
		blocks = append(blocks, MarkdownBlock{
			Kind:     "code",
			Content:  strings.Join(fenced, "\n"),
			Language: lang,
		})
		fenced = fenced[:0]
		fence, lang = "", ""
	}

	for _, line := range lines {
		if fence != "" { // inside a fence: consume verbatim until it closes
			fenced = append(fenced, line)
			if closingFence(line, fence) {
				flushFence()
			}
			continue
		}
		if f, info, ok := fenceRun(line); ok {
			flushPara()
			fence, lang = f, info
			fenced = append(fenced, line)
			continue
		}
		if strings.TrimSpace(line) == "" { // blank line ends the paragraph
			flushPara()
			continue
		}
		para = append(para, line)
	}
	if fence != "" {
		flushFence() // unterminated fence: code to EOF
	} else {
		flushPara()
	}
	return blocks
}

// CardTitleFromMarkdown extracts a display title from a markdown string: the
// first ATX heading (# .. ######) if present, trimmed of leading #s; otherwise
// the first non-empty line, truncated to maxLen runes (and suffixed with "…"
// when truncated). Basic inline noise (leading/trailing *, _ and backticks) is
// stripped from the extracted title. maxLen <= 0 falls back to 40 runes, and
// "huan-agent" is returned when nothing usable exists.
//
// Headings are only honoured outside fenced code blocks, so a "# comment" line
// inside a code sample cannot become the card title. Truncation is on rune
// boundaries, so multi-byte text (e.g. Chinese) stays valid UTF-8.
func CardTitleFromMarkdown(md string, maxLen int) string {
	if maxLen <= 0 {
		maxLen = defaultCardTitleMaxLen
	}

	title, firstLine := "", ""
	for _, b := range SplitMarkdownBlocks(md) {
		if b.Kind != "text" {
			continue
		}
		for _, line := range strings.Split(b.Content, "\n") {
			if firstLine == "" {
				firstLine = strings.TrimSpace(line)
			}
			if _, text, ok := atxHeading(line); ok && text != "" {
				title = text
				break
			}
		}
		if title != "" {
			break
		}
	}
	if title == "" {
		title = firstLine
	}
	if title == "" {
		// No heading and no text block at all (the input is code only): use the
		// first non-empty line that is not a fence delimiter.
		for _, line := range strings.Split(normalizeNewlines(md), "\n") {
			t := strings.TrimSpace(line)
			if t == "" || strings.HasPrefix(t, "```") || strings.HasPrefix(t, "~~~") {
				continue
			}
			title = t
			break
		}
	}

	title = strings.TrimSpace(stripInlineMarkdown(title))
	if strings.Trim(title, "#") == "" {
		// Nothing usable: empty, or a bare run of heading markers such as "#".
		return defaultCardTitle
	}
	return truncateRunes(title, maxLen)
}

// normalizeNewlines converts CRLF and lone CR line endings to LF.
func normalizeNewlines(s string) string {
	if !strings.ContainsRune(s, '\r') {
		return s
	}
	s = strings.ReplaceAll(s, "\r\n", "\n")
	return strings.ReplaceAll(s, "\r", "\n")
}

// fenceRun detects a fenced-code opening line. It returns the run of fence
// characters (```/~~~ plus any extras, which must be matched when closing), the
// trimmed info string, and whether the line opens a fence at all.
//
// CommonMark allows up to three leading spaces; we accept any indentation to
// stay lenient with model-generated markdown.
func fenceRun(line string) (fence, info string, ok bool) {
	t := strings.TrimLeft(line, " \t")
	if t == "" || (t[0] != '`' && t[0] != '~') {
		return "", "", false
	}
	c := t[0]
	n := 0
	for n < len(t) && t[n] == c {
		n++
	}
	if n < 3 {
		return "", "", false
	}
	rest := t[n:]
	// A backtick fence's info string must not contain a backtick (CommonMark).
	if c == '`' && strings.IndexByte(rest, '`') >= 0 {
		return "", "", false
	}
	return t[:n], strings.TrimSpace(rest), true
}

// closingFence reports whether line closes a fence opened with fence: same
// fence character, at least as long, and nothing but whitespace after it.
func closingFence(line, fence string) bool {
	if fence == "" {
		return false
	}
	t := strings.TrimLeft(line, " \t")
	c := fence[0]
	n := 0
	for n < len(t) && t[n] == c {
		n++
	}
	if n < len(fence) {
		return false
	}
	return strings.TrimSpace(t[n:]) == ""
}

// atxHeading reports whether line is an ATX heading and returns its level and
// its text with the leading #s and any closing #s removed.
func atxHeading(line string) (level int, text string, ok bool) {
	t := strings.TrimLeft(line, " \t")
	n := 0
	for n < len(t) && t[n] == '#' {
		n++
	}
	if n == 0 || n > 6 {
		return 0, "", false
	}
	rest := t[n:]
	// "#hashtag" is not a heading: the #s must be followed by a space or EOL.
	if rest != "" && rest[0] != ' ' && rest[0] != '\t' {
		return 0, "", false
	}
	text = strings.TrimSpace(rest)
	text = strings.TrimSpace(strings.TrimRight(text, "#"))
	return n, text, true
}

// stripInlineMarkdown removes basic inline markdown noise (leading/trailing
// *, _ and backticks, plus surrounding whitespace) from a title.
func stripInlineMarkdown(s string) string {
	return strings.Trim(s, " \t*_`")
}

// truncateRunes cuts s to at most maxLen runes, appending "…" when it was
// truncated. Cutting on rune boundaries keeps the result valid UTF-8.
func truncateRunes(s string, maxLen int) string {
	if maxLen <= 0 || utf8.RuneCountInString(s) <= maxLen {
		return s
	}
	runes := []rune(s)
	return strings.TrimRight(string(runes[:maxLen]), " \t") + "…"
}

// splitCodeBlock splits an oversized fenced code block into several parts that
// each fit the budget and stay valid fenced markdown: every part re-opens the
// opening fence (info string included) and re-closes it.
func splitCodeBlock(b MarkdownBlock) []string {
	lines := strings.Split(b.Content, "\n")
	fence, info, ok := fenceRun(lines[0])
	open, close := fence+info, fence
	overhead := len(open) + len(close) + 2 // the two "\n" around the body

	// Either the first line is no fence opener at all, or the fence alone
	// already exhausts the budget (an absurdly long info string). Neither can be
	// re-fenced usefully, so fall back to a plain split.
	if !ok || overhead+1 > MaxCardContentBytes {
		return splitContentByLines(b.Content, MaxCardContentBytes)
	}

	body := lines[1:]
	if n := len(body); n > 0 && closingFence(body[n-1], fence) {
		body = body[:n-1]
	}

	groups := groupLines(body, MaxCardContentBytes-overhead)
	parts := make([]string, 0, len(groups))
	for _, g := range groups {
		parts = append(parts, open+"\n"+strings.Join(g, "\n")+"\n"+close)
	}
	return parts
}

// splitContentByLines splits text into chunks of at most maxBytes, cutting only
// at line boundaries. Joining the result with "\n" reproduces text exactly,
// unless a single line is itself larger than maxBytes, in which case that line
// is broken on a rune boundary so the budget still holds.
func splitContentByLines(text string, maxBytes int) []string {
	if maxBytes <= 0 {
		maxBytes = MaxCardContentBytes
	}
	if len(text) <= maxBytes {
		return []string{text}
	}
	groups := groupLines(strings.Split(text, "\n"), maxBytes)
	parts := make([]string, 0, len(groups))
	for _, g := range groups {
		parts = append(parts, strings.Join(g, "\n"))
	}
	return parts
}

// groupLines greedily groups lines so that strings.Join(group, "\n") never
// exceeds maxBytes. A line larger than maxBytes is first broken into rune-safe
// pieces of at most maxBytes, each piece counting as its own line.
func groupLines(lines []string, maxBytes int) [][]string {
	if maxBytes <= 0 {
		maxBytes = utf8.UTFMax
	}
	groups := make([][]string, 0, 4)
	var cur []string
	curLen := 0
	flush := func() {
		if len(cur) > 0 {
			groups = append(groups, cur)
			cur, curLen = nil, 0
		}
	}
	for _, line := range lines {
		for _, piece := range splitLongLine(line, maxBytes) {
			need := len(piece)
			if len(cur) > 0 {
				need++ // the "\n" joining this piece to the previous line
			}
			if curLen+need > maxBytes {
				flush()
				need = len(piece)
			}
			cur = append(cur, piece)
			curLen += need
		}
	}
	flush()
	return groups
}

// splitLongLine breaks s into pieces of at most maxBytes without ever splitting
// a rune. Short lines are returned unchanged.
func splitLongLine(s string, maxBytes int) []string {
	if maxBytes < utf8.UTFMax {
		maxBytes = utf8.UTFMax
	}
	if len(s) <= maxBytes {
		return []string{s}
	}
	pieces := make([]string, 0, len(s)/maxBytes+1)
	for len(s) > maxBytes {
		cut := maxBytes
		for cut > 0 && !utf8.RuneStart(s[cut]) {
			cut--
		}
		if cut == 0 { // defensive: only reachable with invalid UTF-8 input
			cut = maxBytes
		}
		pieces = append(pieces, s[:cut])
		s = s[cut:]
	}
	return append(pieces, s)
}
