// Package artifact stores the resources the agent produces while it works.
//
// An artifact is what is left over after a task that is neither code nor project
// documentation: an HTML page the agent built to show something, a report, a CSV,
// a chart, a picture. Those used to have no home — write_file could put them in
// the workspace, but the workspace is the user's project, and a generated page
// sitting among its sources is clutter that also cannot be reached from a
// browser.
//
// # What this package owns
//
//   - where an artifact's bytes live (Root, one directory outside the
//     workspaces), and the path rules that keep a write — and a read — inside it;
//   - what a path looks like: <session>/<timestamp>-<slug>.<ext>, so the store is
//     browsable by a person with `ls` and a deleted database row does not make the
//     file unrecognisable;
//   - the content type a file is served as, derived from its extension and
//     never from anything a client said.
//
// # What it deliberately does not own
//
// The database row. A Store writes the bytes and returns where they went; the
// caller (internal/server) records the row, because the searchable index is also
// what the console lists, and putting SQLite behind this interface would make the
// package that implements file layout depend on the schema that indexes it.
//
// # Sessions
//
// A session here is an opaque owner token — a chat session id, or a one-shot
// run's id — not a foreign key. It is part of the path prefix, which is what
// makes "this conversation's artifacts" a directory operation rather than a
// query, and what keeps two sessions' files from colliding on a name.
package artifact

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/huan/huan-agent/internal/store"
)

// Limits and defaults.
const (
	// DefaultMaxBytes caps one artifact. 32 MiB holds a generated page with
	// inlined images, a long report or a screenshot, and is the point past which
	// the console's download URL stops being the right way to hand something over.
	DefaultMaxBytes int64 = 32 << 20
	// maxSlug bounds the file-name slug derived from a title, so a title that is
	// a whole paragraph does not become a whole-paragraph file name.
	maxSlug = 48
	// maxTitle bounds the title recorded for display, for the same reason.
	maxTitle = 200
	// maxSession bounds an owner token before it is used as a path component.
	// A session id is generated by this program and is short; the bound exists so
	// that a future caller cannot turn one into a path-length failure.
	maxSession = 64
	// tempPattern names the intermediate file of the atomic write. Hidden and
	// distinctive, and in the destination directory so the rename stays on one
	// filesystem (a cross-device rename is not atomic).
	tempPattern = ".huan-agent-artifact-*"
)

// ErrDisabled reports that no store root is configured.
var ErrDisabled = errors.New("artifact: store is not configured")

// ErrOutsideRoot reports a path that does not stay inside the store root. It is
// a corrupted row or a bug, never a client mistake.
var ErrOutsideRoot = errors.New("artifact: path is outside the artifact root")

// Store reads and writes artifact bytes under one root directory.
type Store struct {
	root     string
	maxBytes int64
}

// Options configures a Store.
type Options struct {
	// MaxBytes caps one artifact. Zero uses DefaultMaxBytes.
	MaxBytes int64
}

// New returns a Store rooted at root, creating the directory if needed.
//
// An empty root is refused rather than defaulted: this writes files to disk, and
// a deployment that did not say where should be told so rather than have a
// directory chosen for it. Callers that treat "not configured" as a supported
// state check the config before calling.
func New(root string, opts Options) (*Store, error) {
	root = strings.TrimSpace(root)
	if root == "" {
		return nil, ErrDisabled
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("artifact: resolve root %q: %w", root, err)
	}
	if err := os.MkdirAll(abs, 0o755); err != nil {
		return nil, fmt.Errorf("artifact: create root %q: %w", abs, err)
	}
	// Resolve symlinks on the root itself, now that it exists. Without this the
	// containment check compares a resolved child against an unresolved root and
	// rejects everything under it — which is exactly what happens on macOS, where
	// a temp directory is under /var, a symlink to /private/var. The workspace
	// sandbox does the same thing for the same reason.
	if resolved, rerr := filepath.EvalSymlinks(abs); rerr == nil {
		abs = resolved
	} else {
		return nil, fmt.Errorf("artifact: resolve root symlinks: %w", rerr)
	}
	maxBytes := opts.MaxBytes
	if maxBytes <= 0 {
		maxBytes = DefaultMaxBytes
	}
	return &Store{root: abs, maxBytes: maxBytes}, nil
}

// Root reports the absolute directory artifacts are stored under.
func (s *Store) Root() string {
	if s == nil {
		return ""
	}
	return s.root
}

// MaxBytes reports the size cap applied to one artifact.
func (s *Store) MaxBytes() int64 {
	if s == nil {
		return DefaultMaxBytes
	}
	return s.maxBytes
}

// SaveInput is one artifact about to be stored.
type SaveInput struct {
	// Title is the human label. It supplies the file name's slug and is recorded
	// for display; it is never a path component on its own.
	Title string
	// SessionID owns the artifact and becomes the first path component. It is
	// optional: an artifact with no session lands in the store's root, which is
	// what a one-shot run produces.
	SessionID string
	// Name suggests a file name (e.g. "report.html"). The extension picks the
	// stored extension and therefore the content type; the stem is used only
	// when Title gives no slug. Optional.
	Name string
	// Kind is the store's artifact kind (store.ArtifactKind*). Empty is inferred
	// from the extension.
	Kind string
}

// Result is a stored artifact, minus the database row.
type Result struct {
	// Path is the artifact's location relative to Root, in slash form. It is
	// what the serving route resolves and what the row records.
	Path string
	// MIME is the content type the file is served as.
	MIME string
	// Kind is the artifact kind, inferred from the extension when the input did
	// not say.
	Kind string
	// Bytes is how much was written.
	Bytes int64
}

// Save writes one artifact, returning where it landed.
//
// The write is atomic (temp file + rename) and bounded: content larger than the
// cap is refused rather than truncated. The caller records the returned path in
// the database; a failure after this returns leaves a file with no row, which is
// the harmless direction (the store is browsable and the console simply does not
// list it).
func (s *Store) Save(in SaveInput, content io.Reader) (Result, error) {
	if s == nil {
		return Result{}, ErrDisabled
	}
	if content == nil {
		return Result{}, errors.New("artifact: content is required")
	}

	session, err := sessionComponent(in.SessionID)
	if err != nil {
		return Result{}, err
	}
	ext, mime, err := resolveType(in.Name, in.Kind)
	if err != nil {
		return Result{}, err
	}
	kind := normalizeKind(in.Kind, ext)
	title := truncateRunes(strings.TrimSpace(in.Title), maxTitle)

	dir := s.root
	if session != "" {
		dir = filepath.Join(s.root, session)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return Result{}, fmt.Errorf("artifact: create session directory: %w", err)
		}
	}

	slug := slugify(title)
	if slug == "" {
		// No title, or a title with nothing nameable in it (a Chinese title has
		// no ASCII letters — slugify says so, and the id below is what names the
		// file instead). The file is still addressable; only its name is opaque.
		slug = randomToken(6)
	}
	name := fmt.Sprintf("%s-%s%s", time.Now().UTC().Format("20060102-150405"), slug, ext)
	rel := name
	if session != "" {
		rel = session + "/" + name
	}

	abs, err := s.Resolve(rel)
	if err != nil {
		return Result{}, err
	}

	written, err := writeAtomic(abs, content, s.maxBytes)
	if err != nil {
		return Result{}, err
	}
	return Result{Path: rel, MIME: mime, Kind: kind, Bytes: written}, nil
}

// Resolve turns a stored relative path into an absolute one, refusing anything
// that leaves the root.
//
// Every read and every write goes through here. The rules are the workspace
// sandbox's (see internal/workspace): reject NUL, clean first, refuse an absolute
// path, refuse a traversal, and re-check after resolving symlinks — because the
// artifact store is on the server's own disk and a path that escapes it is a read
// of the server's filesystem, not of a product.
func (s *Store) Resolve(rel string) (string, error) {
	if s == nil {
		return "", ErrDisabled
	}
	if strings.ContainsRune(rel, 0) {
		return "", fmt.Errorf("%w: contains a NUL byte", ErrOutsideRoot)
	}
	rel = strings.TrimSpace(rel)
	if rel == "" {
		return "", fmt.Errorf("%w: empty", ErrOutsideRoot)
	}
	if path.IsAbs(rel) || filepath.IsAbs(rel) {
		return "", fmt.Errorf("%w: %s", ErrOutsideRoot, rel)
	}
	// Slash form is what the routes carry; a backslash is a Windows separator and
	// a name made only of separators is not a path.
	clean := path.Clean(strings.ReplaceAll(rel, "\\", "/"))
	if clean == "." || clean == ".." || strings.HasPrefix(clean, "../") {
		return "", fmt.Errorf("%w: %s", ErrOutsideRoot, rel)
	}

	abs := filepath.Join(s.root, filepath.FromSlash(clean))
	if !s.contains(abs) {
		return "", fmt.Errorf("%w: %s", ErrOutsideRoot, rel)
	}
	// Re-check through symlinks on the part that exists, so a symlink inside the
	// root cannot be used to read or overwrite something outside it.
	resolved, err := resolveExisting(abs)
	if err != nil {
		return "", err
	}
	if !s.contains(resolved) {
		return "", fmt.Errorf("%w: %s resolves outside the root", ErrOutsideRoot, rel)
	}
	return abs, nil
}

// Open returns the file at a stored relative path for reading.
func (s *Store) Open(rel string) (*os.File, int64, error) {
	abs, err := s.Resolve(rel)
	if err != nil {
		return nil, 0, err
	}
	f, err := os.Open(abs)
	if err != nil {
		return nil, 0, err
	}
	info, err := f.Stat()
	if err != nil {
		_ = f.Close()
		return nil, 0, err
	}
	// A directory is not an artifact; answering with one would make the serving
	// route's Content-Length meaningless.
	if info.IsDir() {
		_ = f.Close()
		return nil, 0, fmt.Errorf("artifact: %s is a directory", rel)
	}
	return f, info.Size(), nil
}

// Remove deletes one artifact's bytes. A missing file is not an error: the
// caller is removing a row, and a file the operator already deleted by hand
// should not make that fail.
func (s *Store) Remove(rel string) error {
	abs, err := s.Resolve(rel)
	if err != nil {
		return err
	}
	if err := os.Remove(abs); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("artifact: remove %s: %w", rel, err)
	}
	return nil
}

// contains reports whether abs is the root or inside it.
func (s *Store) contains(abs string) bool {
	if abs == s.root {
		return true
	}
	rel, err := filepath.Rel(s.root, abs)
	if err != nil {
		return false
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return false
	}
	return !filepath.IsAbs(rel)
}

// resolveExisting resolves symlinks on the longest existing prefix of p, so a
// path whose final component does not exist yet can still be validated.
func resolveExisting(p string) (string, error) {
	cur := p
	var tail []string
	for {
		resolved, err := filepath.EvalSymlinks(cur)
		if err == nil {
			if len(tail) == 0 {
				return resolved, nil
			}
			parts := append([]string{resolved}, tail...)
			return filepath.Join(parts...), nil
		}
		if !os.IsNotExist(err) {
			return "", fmt.Errorf("artifact: resolve %s: %w", p, err)
		}
		parent := filepath.Dir(cur)
		if parent == cur {
			// Walked to the root without finding anything that exists.
			return p, nil
		}
		tail = append([]string{filepath.Base(cur)}, tail...)
		cur = parent
	}
}

// writeAtomic writes content to dst through a temp file in the same directory,
// capped at maxBytes.
func writeAtomic(dst string, content io.Reader, maxBytes int64) (int64, error) {
	dir := filepath.Dir(dst)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return 0, fmt.Errorf("artifact: create directory %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, tempPattern)
	if err != nil {
		return 0, fmt.Errorf("artifact: create temp file: %w", err)
	}
	tmpName := tmp.Name()
	// Remove the temp file on any failure path; the successful path renames it.
	defer func() {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
	}()

	// One byte past the cap is read so "exactly at the limit" and "over it" can
	// be told apart, and the message can say which.
	written, err := io.Copy(tmp, io.LimitReader(content, maxBytes+1))
	if err != nil {
		return 0, fmt.Errorf("artifact: write: %w", err)
	}
	if written > maxBytes {
		return 0, fmt.Errorf("artifact: content is over the %d byte limit", maxBytes)
	}
	if err := tmp.Close(); err != nil {
		return 0, fmt.Errorf("artifact: close temp file: %w", err)
	}
	// 0644: an artifact is served over HTTP and read by the operator, and it is
	// not a secret — the login gate, not the file mode, is what protects it.
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return 0, fmt.Errorf("artifact: chmod temp file: %w", err)
	}
	if err := os.Rename(tmpName, dst); err != nil {
		return 0, fmt.Errorf("artifact: rename into place: %w", err)
	}
	return written, nil
}

// sessionComponent validates an owner token and returns it as a path component.
func sessionComponent(sessionID string) (string, error) {
	s := strings.TrimSpace(sessionID)
	if s == "" {
		return "", nil
	}
	if len(s) > maxSession {
		return "", fmt.Errorf("artifact: session id is longer than %d bytes", maxSession)
	}
	// A session id becomes a single path component, so anything that is not a
	// letter, digit, dash or underscore is refused rather than escaped: this
	// program generates the ids, and a caller passing a path is a bug.
	for i := 0; i < len(s); i++ {
		c := s[i]
		ok := c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '-' || c == '_'
		if !ok {
			return "", fmt.Errorf("artifact: session id %q contains a character that is not allowed in a path", s)
		}
	}
	return s, nil
}

// resolveType picks the stored extension and content type.
//
// A file name with an extension decides both. Failing one, the kind does, and a
// request that named neither is stored as HTML — the case this feature exists
// for is a page the agent built. An extension this build does not know is
// refused rather than stored: it would be served as an opaque download, which is
// not what "save this so it can be opened" means.
func resolveType(name, kind string) (ext, mime string, err error) {
	ext = strings.ToLower(strings.TrimSpace(path.Ext(strings.TrimSpace(name))))
	if ext == "" {
		ext = ExtForKind(normalizeKind(kind, ""))
	}
	if !strings.HasPrefix(ext, ".") {
		ext = "." + ext
	}
	mime, ok := mimeByExt[ext]
	if !ok {
		return "", "", fmt.Errorf("artifact: %s is not a supported artifact type (%s)", ext,
			strings.Join(supportedExts(), " / "))
	}
	return ext, mime, nil
}

// normalizeKind returns the artifact kind to record: what the caller said when it
// is valid, otherwise the one implied by the extension.
//
// A request that named neither a kind nor a file name resolves to HTML, which is
// the case this feature exists for — a page the agent built. It is the same
// default resolveType takes, deliberately: the kind decides the extension and the
// extension decides the kind, so the two have to agree on the empty input.
func normalizeKind(kind, ext string) string {
	switch kind {
	case store.ArtifactKindHTML, store.ArtifactKindDocument, store.ArtifactKindImage, store.ArtifactKindOther:
		return kind
	}
	if implied, ok := kindByExt[ext]; ok {
		return implied
	}
	if ext == "" {
		return store.ArtifactKindHTML
	}
	return store.ArtifactKindOther
}

// MIMEByExt reports the content type this build serves a file with, and whether
// the extension is a supported artifact type at all.
//
// Exported because the serving route has to answer the same question as the write
// path: what a stored file is, is decided here once.
func MIMEByExt(ext string) (string, bool) {
	if ext == "" {
		return "", false
	}
	if !strings.HasPrefix(ext, ".") {
		ext = "." + ext
	}
	mime, ok := mimeByExt[strings.ToLower(ext)]
	return mime, ok
}

// MIMEForPath reports the content type a stored path is served with.
func MIMEForPath(p string) (string, bool) {
	return MIMEByExt(strings.ToLower(path.Ext(p)))
}

// mimeByExt is the whole accepted set. Everything here is something a browser
// renders or a person opens; nothing here is ever served with a type that could
// make a browser treat it as a program (no SVG, no JS, no HTML masquerading as
// text — see the serving route for the headers that back that up).
var mimeByExt = map[string]string{
	".html": "text/html; charset=utf-8",
	".htm":  "text/html; charset=utf-8",
	".md":   "text/markdown; charset=utf-8",
	".txt":  "text/plain; charset=utf-8",
	".csv":  "text/csv; charset=utf-8",
	".json": "application/json",
	".xml":  "application/xml",

	".png":  "image/png",
	".jpg":  "image/jpeg",
	".jpeg": "image/jpeg",
	".gif":  "image/gif",
	".webp": "image/webp",

	".pdf": "application/pdf",
}

// kindByExt groups the accepted extensions for the console's icons and filters.
var kindByExt = map[string]string{
	".html": store.ArtifactKindHTML,
	".htm":  store.ArtifactKindHTML,

	".md":   store.ArtifactKindDocument,
	".txt":  store.ArtifactKindDocument,
	".csv":  store.ArtifactKindDocument,
	".json": store.ArtifactKindDocument,
	".xml":  store.ArtifactKindDocument,
	".pdf":  store.ArtifactKindDocument,

	".png":  store.ArtifactKindImage,
	".jpg":  store.ArtifactKindImage,
	".jpeg": store.ArtifactKindImage,
	".gif":  store.ArtifactKindImage,
	".webp": store.ArtifactKindImage,
}

// supportedExts lists the accepted extensions for an error message. Sorted by
// the map's keys having a natural order below — Go randomises map iteration, and
// an error whose list reshuffles between runs is a bad error.
func supportedExts() []string {
	return []string{".html", ".md", ".txt", ".csv", ".json", ".xml", ".png", ".jpg", ".gif", ".webp", ".pdf"}
}

// kindExts is the stored extension per kind, used when a caller gave a kind but
// no file name. Keeping it next to mimeByExt is what stops the two from drifting.
var kindExts = map[string]string{
	store.ArtifactKindHTML:     ".html",
	store.ArtifactKindDocument: ".md",
	store.ArtifactKindImage:    ".png",
	store.ArtifactKindOther:    ".txt",
}

// ExtForKind reports the default stored extension for a kind.
func ExtForKind(kind string) string {
	if ext, ok := kindExts[kind]; ok {
		return ext
	}
	return ".html"
}

// slugify turns a title into a file-name-safe stem.
//
// It keeps ASCII letters, digits, dashes and underscores, folds everything else
// into a single dash, and returns "" when nothing nameable is left — a Chinese
// title produces an empty slug on purpose, and the caller names the file by a
// random token instead. Transliterating Chinese into pinyin here would be a
// dependency and a guess; a short opaque name is honest about being one.
func slugify(title string) string {
	var b strings.Builder
	lastDash := true // leading dashes are dropped
	for _, r := range strings.ToLower(title) {
		switch {
		case r >= 'a' && r <= 'z' || r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		case r == '_':
			if !lastDash {
				b.WriteRune(r)
			}
		default:
			if !lastDash {
				b.WriteRune('-')
				lastDash = true
			}
		}
		if b.Len() >= maxSlug {
			break
		}
	}
	return strings.Trim(b.String(), "-_")
}

// truncateRunes cuts s to at most n runes, counting runes rather than bytes so a
// multi-byte title is not cut mid-character.
func truncateRunes(s string, n int) string {
	if utf8.RuneCountInString(s) <= n {
		return s
	}
	count := 0
	for i := range s {
		count++
		if count > n {
			return strings.TrimSpace(s[:i])
		}
	}
	return s
}

// randomToken returns n bytes of hex randomness, used to name a file whose title
// gave no slug.
func randomToken(n int) string {
	buf := make([]byte, (n+1)/2)
	if _, err := rand.Read(buf); err != nil {
		// crypto/rand does not fail in practice on the platforms this runs on;
		// a fallback based on the clock is still better than an empty name,
		// because the caller is about to write a file.
		return fmt.Sprintf("%x", time.Now().UnixNano())[:n]
	}
	return hex.EncodeToString(buf)[:n]
}

// URL returns the path an artifact is served at for a console mounted at the
// given prefix, escaping each path segment.
//
// It is built here rather than at each call site so the console's links and the
// serving route cannot disagree about the shape of an address.
func URL(prefix, rel string) string {
	prefix = strings.TrimSuffix(prefix, "/")
	segments := strings.Split(strings.TrimPrefix(path.Clean("/"+rel), "/"), "/")
	escaped := make([]string, 0, len(segments))
	for _, s := range segments {
		if s == "" {
			continue
		}
		escaped = append(escaped, url.PathEscape(s))
	}
	return prefix + "/" + strings.Join(escaped, "/")
}
